### ISSUE TITLE
Templates downloading broken if user doesn't have git installed

### ISSUE THREAD

**Issue by R4ph3rd** [AtelierNum/fido#5]
As mentionned in this [ticket](https://github.com/npm/npm/issues/10894), pointing towards to a zip or a tarball and unpack it instead of using Git cli through Nodejs package can be a easy solution.

**Comment by zhakkarn** [comment]
try querying https://github.com/AtelierNum/templates/archive/main/Unity.tar.gz , it'll pull the whole repo instead of just the Unity templates

**Comment by R4ph3rd** [comment]
https://github.com/KinoLien/gitzip
https://github.com/MinhasKamal/DownGit
Might be interesting to take a look at these tools to see how they're doing. They can download & zip subfolders from a github repo.

**Comment by zhakk-harn** [comment]
fixed by making this https://www.npmjs.com/package/degitdegit
